// <auto-generated />
using System;
using CarPark.Infrastructure.Persistence.Db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CarPark.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251020124117_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CarPark.Domain.Entities.ParkingSpace", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsOccupied")
                        .HasColumnType("boolean");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("TimeInUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VehicleReg")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int?>("VehicleType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Number")
                        .IsUnique();

                    b.ToTable("parking_spaces", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("8a034a28-268e-49ca-8148-f047ae7cecca"),
                            IsOccupied = false,
                            Number = 1
                        },
                        new
                        {
                            Id = new Guid("82c51759-0a6b-480c-8195-77561bae24ac"),
                            IsOccupied = false,
                            Number = 2
                        },
                        new
                        {
                            Id = new Guid("b677216a-19f5-4cdc-9cff-f447a95cc5a0"),
                            IsOccupied = false,
                            Number = 3
                        },
                        new
                        {
                            Id = new Guid("a17a644b-6879-4dad-b942-2a406e809ed0"),
                            IsOccupied = false,
                            Number = 4
                        },
                        new
                        {
                            Id = new Guid("091e4237-677b-4a86-b059-3559469922b6"),
                            IsOccupied = false,
                            Number = 5
                        },
                        new
                        {
                            Id = new Guid("a25b34d7-ba63-45ca-8e5a-f3ace7ec62cc"),
                            IsOccupied = false,
                            Number = 6
                        },
                        new
                        {
                            Id = new Guid("2cc93342-a25e-4787-862f-139e5a7a86cc"),
                            IsOccupied = false,
                            Number = 7
                        },
                        new
                        {
                            Id = new Guid("e137b613-6f97-4246-9ae6-713e0a975cc0"),
                            IsOccupied = false,
                            Number = 8
                        },
                        new
                        {
                            Id = new Guid("e2170b3b-477f-4ce6-b92a-085a77dbdca9"),
                            IsOccupied = false,
                            Number = 9
                        },
                        new
                        {
                            Id = new Guid("794208bc-1aef-4681-ae6c-8442ae8afcea"),
                            IsOccupied = false,
                            Number = 10
                        },
                        new
                        {
                            Id = new Guid("f3d6eb98-6573-4703-8597-45f96037aa1b"),
                            IsOccupied = false,
                            Number = 11
                        },
                        new
                        {
                            Id = new Guid("549fae87-797b-46e9-b950-1b3b5b2f6dea"),
                            IsOccupied = false,
                            Number = 12
                        },
                        new
                        {
                            Id = new Guid("395b96e5-6cf6-4255-a846-1b3604d2908d"),
                            IsOccupied = false,
                            Number = 13
                        },
                        new
                        {
                            Id = new Guid("94091e3a-2b8d-4572-98d5-e2fb8f55ce83"),
                            IsOccupied = false,
                            Number = 14
                        },
                        new
                        {
                            Id = new Guid("01fb0b51-5393-40c2-a56e-244127f91c96"),
                            IsOccupied = false,
                            Number = 15
                        },
                        new
                        {
                            Id = new Guid("61d53d20-ff4c-405a-9b2f-b59e082a5a5f"),
                            IsOccupied = false,
                            Number = 16
                        },
                        new
                        {
                            Id = new Guid("5cbd6b9d-5710-432d-93b3-7f9c7456ed9c"),
                            IsOccupied = false,
                            Number = 17
                        },
                        new
                        {
                            Id = new Guid("8ce880ab-80a1-442f-a2bc-e98c465b562f"),
                            IsOccupied = false,
                            Number = 18
                        },
                        new
                        {
                            Id = new Guid("5273c4a7-2451-4f5e-8215-eae60caa4c3f"),
                            IsOccupied = false,
                            Number = 19
                        },
                        new
                        {
                            Id = new Guid("c926fc9a-933e-4373-873e-1f639287e91e"),
                            IsOccupied = false,
                            Number = 20
                        },
                        new
                        {
                            Id = new Guid("2eef1941-2268-42d1-b681-4ba0196f6405"),
                            IsOccupied = false,
                            Number = 21
                        },
                        new
                        {
                            Id = new Guid("ba7a624f-317e-423f-b0c0-0ec41e7d46f1"),
                            IsOccupied = false,
                            Number = 22
                        },
                        new
                        {
                            Id = new Guid("faae4734-1527-4fd8-ac94-692041264229"),
                            IsOccupied = false,
                            Number = 23
                        },
                        new
                        {
                            Id = new Guid("b8c4ee61-af76-4453-802f-67bf0101e35a"),
                            IsOccupied = false,
                            Number = 24
                        },
                        new
                        {
                            Id = new Guid("86ee41ae-6bf3-41d3-ae35-51115f92ead4"),
                            IsOccupied = false,
                            Number = 25
                        },
                        new
                        {
                            Id = new Guid("b907d703-da11-4034-b4d6-1be54344e77e"),
                            IsOccupied = false,
                            Number = 26
                        },
                        new
                        {
                            Id = new Guid("27bfd5a6-1291-4361-bd54-fa0d54b4fcfe"),
                            IsOccupied = false,
                            Number = 27
                        },
                        new
                        {
                            Id = new Guid("31543c78-d436-4257-9961-d26319c561ee"),
                            IsOccupied = false,
                            Number = 28
                        },
                        new
                        {
                            Id = new Guid("9a5e3072-3de1-40f8-9578-b0cbbb13a1b2"),
                            IsOccupied = false,
                            Number = 29
                        },
                        new
                        {
                            Id = new Guid("ea75fdf6-5591-4372-9778-8adf58a4e573"),
                            IsOccupied = false,
                            Number = 30
                        },
                        new
                        {
                            Id = new Guid("7772a2d1-52c0-4357-a081-ef2b7fbac321"),
                            IsOccupied = false,
                            Number = 31
                        },
                        new
                        {
                            Id = new Guid("00e1be6f-f963-4ece-8efb-bc6edb12e62d"),
                            IsOccupied = false,
                            Number = 32
                        },
                        new
                        {
                            Id = new Guid("77f1f8aa-3988-49c8-bf93-3b75984bf54a"),
                            IsOccupied = false,
                            Number = 33
                        },
                        new
                        {
                            Id = new Guid("38607bc4-4587-4852-b3c6-9e9e1950d354"),
                            IsOccupied = false,
                            Number = 34
                        },
                        new
                        {
                            Id = new Guid("21c406c7-07c0-4315-9d3e-9bfd0e5c1a17"),
                            IsOccupied = false,
                            Number = 35
                        },
                        new
                        {
                            Id = new Guid("c6cc8b6a-bccd-40f1-a71e-94d09a5d65d1"),
                            IsOccupied = false,
                            Number = 36
                        },
                        new
                        {
                            Id = new Guid("4be032dd-c172-466a-9ba6-031ac4a49665"),
                            IsOccupied = false,
                            Number = 37
                        },
                        new
                        {
                            Id = new Guid("20da0a11-722a-421a-8ac2-26c515e32b66"),
                            IsOccupied = false,
                            Number = 38
                        },
                        new
                        {
                            Id = new Guid("8f25583b-ee04-42bb-b218-3d9dce372387"),
                            IsOccupied = false,
                            Number = 39
                        },
                        new
                        {
                            Id = new Guid("38c7b302-5287-4aa3-9c42-edeb8487ef25"),
                            IsOccupied = false,
                            Number = 40
                        },
                        new
                        {
                            Id = new Guid("29c103b4-7333-4909-b79d-18b33421238c"),
                            IsOccupied = false,
                            Number = 41
                        },
                        new
                        {
                            Id = new Guid("7b6e58cc-e915-48fa-a26c-8278ebee9964"),
                            IsOccupied = false,
                            Number = 42
                        },
                        new
                        {
                            Id = new Guid("b7a2ceb9-6ca5-445e-955d-f45a820a4c45"),
                            IsOccupied = false,
                            Number = 43
                        },
                        new
                        {
                            Id = new Guid("2eda2f24-b572-4d8c-a932-a304e2d2c0e7"),
                            IsOccupied = false,
                            Number = 44
                        },
                        new
                        {
                            Id = new Guid("bc5990b4-076a-44c7-870b-0c7ca19abd5e"),
                            IsOccupied = false,
                            Number = 45
                        },
                        new
                        {
                            Id = new Guid("738a0d7c-63e4-4401-8cca-928c6062e88a"),
                            IsOccupied = false,
                            Number = 46
                        },
                        new
                        {
                            Id = new Guid("4c181e1f-be00-4a32-ae67-f3e100491116"),
                            IsOccupied = false,
                            Number = 47
                        },
                        new
                        {
                            Id = new Guid("fd554804-2f21-497c-9b24-996d39929bef"),
                            IsOccupied = false,
                            Number = 48
                        },
                        new
                        {
                            Id = new Guid("04bbf469-1969-4b09-91c3-befd99f2d297"),
                            IsOccupied = false,
                            Number = 49
                        },
                        new
                        {
                            Id = new Guid("7f8fe01b-e443-45b6-9792-fe903411033a"),
                            IsOccupied = false,
                            Number = 50
                        },
                        new
                        {
                            Id = new Guid("d7589829-5b8b-488d-99e1-8c41d53546a9"),
                            IsOccupied = false,
                            Number = 51
                        },
                        new
                        {
                            Id = new Guid("d50d9979-b107-4608-b8c8-e56f5140217c"),
                            IsOccupied = false,
                            Number = 52
                        },
                        new
                        {
                            Id = new Guid("1d060a53-7452-4988-8ea1-f59184c6d55b"),
                            IsOccupied = false,
                            Number = 53
                        },
                        new
                        {
                            Id = new Guid("7c6efa4f-84ff-454a-a77a-f9bf47e9dca2"),
                            IsOccupied = false,
                            Number = 54
                        },
                        new
                        {
                            Id = new Guid("68c02101-3405-4ea2-8db7-026c00f575fe"),
                            IsOccupied = false,
                            Number = 55
                        },
                        new
                        {
                            Id = new Guid("41f68bf9-006b-4246-8b38-5d5ee6f69c5a"),
                            IsOccupied = false,
                            Number = 56
                        },
                        new
                        {
                            Id = new Guid("f590f29c-f076-4aca-9116-cc24bfdf1665"),
                            IsOccupied = false,
                            Number = 57
                        },
                        new
                        {
                            Id = new Guid("18dd34e9-7486-4c7f-b190-83b543bdddfd"),
                            IsOccupied = false,
                            Number = 58
                        },
                        new
                        {
                            Id = new Guid("29838746-266f-419a-a9b6-08a35939b280"),
                            IsOccupied = false,
                            Number = 59
                        },
                        new
                        {
                            Id = new Guid("079faa95-27dd-457e-ad5c-e312088cdcd8"),
                            IsOccupied = false,
                            Number = 60
                        },
                        new
                        {
                            Id = new Guid("eb8535cd-0e19-4e7d-ae0c-1923f81ec83e"),
                            IsOccupied = false,
                            Number = 61
                        },
                        new
                        {
                            Id = new Guid("9760c218-0df6-432d-aeb9-fd07412e67a0"),
                            IsOccupied = false,
                            Number = 62
                        },
                        new
                        {
                            Id = new Guid("96ea1cf3-a2d8-4491-8b32-195985965538"),
                            IsOccupied = false,
                            Number = 63
                        },
                        new
                        {
                            Id = new Guid("02f8264d-b9b0-481e-882a-676f011ca8ef"),
                            IsOccupied = false,
                            Number = 64
                        },
                        new
                        {
                            Id = new Guid("283dd80d-9ac2-4a94-857f-52c7d4ce0480"),
                            IsOccupied = false,
                            Number = 65
                        },
                        new
                        {
                            Id = new Guid("539ac1ce-0ca5-4f27-9195-82f635f0f6a1"),
                            IsOccupied = false,
                            Number = 66
                        },
                        new
                        {
                            Id = new Guid("131755c6-23de-4ee8-99c8-8e80c4cdc463"),
                            IsOccupied = false,
                            Number = 67
                        },
                        new
                        {
                            Id = new Guid("f522f3f3-efe8-475c-8a24-921aaecf2a66"),
                            IsOccupied = false,
                            Number = 68
                        },
                        new
                        {
                            Id = new Guid("269f0011-45b2-4c95-8d95-134645be320b"),
                            IsOccupied = false,
                            Number = 69
                        },
                        new
                        {
                            Id = new Guid("692b5ec0-62e4-4493-b9e1-9d8bcbdec94d"),
                            IsOccupied = false,
                            Number = 70
                        },
                        new
                        {
                            Id = new Guid("7083d813-bf20-4df6-89d8-dd727531bcbd"),
                            IsOccupied = false,
                            Number = 71
                        },
                        new
                        {
                            Id = new Guid("1d2cb018-06e3-4569-a44b-5d3177636a38"),
                            IsOccupied = false,
                            Number = 72
                        },
                        new
                        {
                            Id = new Guid("1eb3288e-a225-4e4c-a6f1-ce0113959603"),
                            IsOccupied = false,
                            Number = 73
                        },
                        new
                        {
                            Id = new Guid("7947a1c3-83e8-4fb0-addc-89f77e3c62b4"),
                            IsOccupied = false,
                            Number = 74
                        },
                        new
                        {
                            Id = new Guid("5a564477-835b-4786-bd92-91ed7e1c16de"),
                            IsOccupied = false,
                            Number = 75
                        },
                        new
                        {
                            Id = new Guid("bdff9b0a-eba7-47ad-adde-7b81cda16b50"),
                            IsOccupied = false,
                            Number = 76
                        },
                        new
                        {
                            Id = new Guid("c8da610a-cfdd-44fc-aaf0-8669e7a56f63"),
                            IsOccupied = false,
                            Number = 77
                        },
                        new
                        {
                            Id = new Guid("72faf6af-b621-46bd-b96b-30ffb1196c1d"),
                            IsOccupied = false,
                            Number = 78
                        },
                        new
                        {
                            Id = new Guid("be88710a-a9c1-4b32-83a2-5ba7e2431831"),
                            IsOccupied = false,
                            Number = 79
                        },
                        new
                        {
                            Id = new Guid("b393a764-f1db-4214-9010-7df2935493f9"),
                            IsOccupied = false,
                            Number = 80
                        },
                        new
                        {
                            Id = new Guid("446b767c-9921-45bb-9fb3-c519f0c731c2"),
                            IsOccupied = false,
                            Number = 81
                        },
                        new
                        {
                            Id = new Guid("e7f8fa74-98a4-448b-9803-3818048a150b"),
                            IsOccupied = false,
                            Number = 82
                        },
                        new
                        {
                            Id = new Guid("7a4c1a85-da70-49c3-ba5e-faab9bdc2c2e"),
                            IsOccupied = false,
                            Number = 83
                        },
                        new
                        {
                            Id = new Guid("ceb5e0a1-b45d-4110-a726-62336d5ab573"),
                            IsOccupied = false,
                            Number = 84
                        },
                        new
                        {
                            Id = new Guid("dc8f0c58-660b-476c-b1cd-a0dbbd9c876f"),
                            IsOccupied = false,
                            Number = 85
                        },
                        new
                        {
                            Id = new Guid("f32ab857-a63f-40ae-8f99-bdf00a9bfaac"),
                            IsOccupied = false,
                            Number = 86
                        },
                        new
                        {
                            Id = new Guid("f15ef783-fce6-42c2-a03c-9c69e773616b"),
                            IsOccupied = false,
                            Number = 87
                        },
                        new
                        {
                            Id = new Guid("8270484c-991d-4d52-8976-bcc8fe803d2e"),
                            IsOccupied = false,
                            Number = 88
                        },
                        new
                        {
                            Id = new Guid("27202a00-8d0e-4674-a9d4-c1e6d6b21e4d"),
                            IsOccupied = false,
                            Number = 89
                        },
                        new
                        {
                            Id = new Guid("9789346f-f263-42f2-a859-fc99bca9bd4e"),
                            IsOccupied = false,
                            Number = 90
                        },
                        new
                        {
                            Id = new Guid("f1a363b2-b5bb-43f2-8065-98045e82146c"),
                            IsOccupied = false,
                            Number = 91
                        },
                        new
                        {
                            Id = new Guid("71fa4b28-c82f-4922-876a-4ec3e3aec41a"),
                            IsOccupied = false,
                            Number = 92
                        },
                        new
                        {
                            Id = new Guid("7c04051d-5afd-47c4-8b33-37ba784b0ef1"),
                            IsOccupied = false,
                            Number = 93
                        },
                        new
                        {
                            Id = new Guid("06e44e57-19df-4b29-b6f9-b4cec2d070c0"),
                            IsOccupied = false,
                            Number = 94
                        },
                        new
                        {
                            Id = new Guid("aa08eea3-853b-4abc-9e94-507b2c25c858"),
                            IsOccupied = false,
                            Number = 95
                        },
                        new
                        {
                            Id = new Guid("3bd5d04d-38e4-4de9-98ce-0762f21dc139"),
                            IsOccupied = false,
                            Number = 96
                        },
                        new
                        {
                            Id = new Guid("a5b4aa67-fa6c-452d-a61c-42b65f3c5a40"),
                            IsOccupied = false,
                            Number = 97
                        },
                        new
                        {
                            Id = new Guid("af87adce-b4d9-449e-9060-a8e7198d9b96"),
                            IsOccupied = false,
                            Number = 98
                        },
                        new
                        {
                            Id = new Guid("e0a9d5cd-cbaf-47d9-9671-e9a69363e4b4"),
                            IsOccupied = false,
                            Number = 99
                        },
                        new
                        {
                            Id = new Guid("c6c5d568-a03d-451f-9c18-d7248b26808e"),
                            IsOccupied = false,
                            Number = 100
                        });
                });

            modelBuilder.Entity("CarPark.Domain.Entities.ParkingTicket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("Charge")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("SpaceNumber")
                        .HasColumnType("integer");

                    b.Property<DateTime>("TimeInUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("TimeOutUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VehicleReg")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("VehicleType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("VehicleReg", "TimeOutUtc")
                        .HasDatabaseName("ix_ticket_vehicle_active");

                    b.ToTable("parking_tickets", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
